# Disease-mediated thermal limits in frogs
# Diele-Viegas et al.
# Script 07. Difference maps

rm(list = ls())
library(terra)
library(tidyverse)

# PATH CONFIGURATIONS 
path <- "G:/My Drive/UMississippi/amphibian_data"
path_bin <- file.path(path, "06_binary")
path_fig2 <- file.path(path, "07_spatial_analysis/Figure2_Temporal")
path_fig4 <- file.path(path, "07_spatial_analysis/Figure4_Overlap")
path_figX <- file.path(path, "07_spatial_analysis/FigureX_Deviation")
path_figY <- file.path(path, "07_spatial_analysis/FigureY_Seasonaloverlap")

dir.create(path_fig2, showWarnings = FALSE, recursive = TRUE)
dir.create(path_fig4, showWarnings = FALSE, recursive = TRUE)
dir.create(path_figX, showWarnings = FALSE, recursive = TRUE)
dir.create(path_figY, showWarnings = FALSE, recursive = TRUE)

# List the binary files generated by the previous script
bin_files <- list.files(path_bin, pattern = "MAX_TSS\\.tif$", full.names = TRUE)

if(length(bin_files) == 0) stop("No binary files found in the 06_binary folder!")

accs <- c("acc17", "acc25")
futures <- c("245", "585") # Adjusted to match the file naming convention

# Figure 2

for(ac in accs) {
  message("\n>>> Processing: ", ac)
  
  # Preparation: Present maps
  file_ni_pres   <- bin_files[grepl(paste0("BIN_", ac, "_noninfected_present"), bin_files)]
  file_i_pres    <- bin_files[grepl(paste0("BIN_", ac, "_infected_present"), bin_files)]
  file_corr_pres <- bin_files[grepl(paste0("BIN_correlative_", ac, "_present"), bin_files)]
  
  r_ni_pres   <- terra::rast(file_ni_pres)
  r_i_pres    <- terra::rast(file_i_pres)
  r_corr_pres <- terra::rast(file_corr_pres)
  
  # FIG 4: Present Overlap
  pres_overlap <- (r_ni_pres * 10) + r_i_pres
  terra::writeRaster(pres_overlap, file.path(path_fig4, paste0("FIG4_Overlap_", ac, "_present.tif")), overwrite=TRUE, datatype = "INT1U")
  
  for(ft in futures) {
    message("  Calculating: ", ft)
    
    # Load Futures
    file_ni_fut   <- bin_files[grepl(paste0("BIN_", ac, "_noninfected_", ft), bin_files)]
    file_i_fut    <- bin_files[grepl(paste0("BIN_", ac, "_infected_", ft), bin_files)]
    file_corr_fut <- bin_files[grepl(paste0("BIN_correlative_", ac, "_", ft), bin_files)]
    
    r_ni_fut   <- terra::rast(file_ni_fut)
    r_i_fut    <- terra::rast(file_i_fut)
    r_corr_fut <- terra::rast(file_corr_fut)
    
    # FIG 4: Future Overlap
    fut_overlap <- (r_ni_fut * 10) + r_i_fut
    terra::writeRaster(fut_overlap, file.path(path_fig4, paste0("FIG4_Overlap_", ac, "_", ft, ".tif")), overwrite=TRUE, datatype = "INT1U")
    
    # FIG 2: Temporal Dynamics (11=Stable, 10=Gain, 1=Loss)
    terra::writeRaster((r_corr_fut * 10) + r_corr_pres, file.path(path_fig2, paste0("FIG2_Temporal_Corr_", ac, "_", ft, ".tif")), overwrite=TRUE, datatype = "INT1U")
    terra::writeRaster((r_ni_fut * 10) + r_ni_pres,     file.path(path_fig2, paste0("FIG2_Temporal_NI_", ac, "_", ft, ".tif")),   overwrite=TRUE, datatype = "INT1U")
    terra::writeRaster((r_i_fut * 10) + r_i_pres,       file.path(path_fig2, paste0("FIG2_Temporal_I_", ac, "_", ft, ".tif")),    overwrite=TRUE, datatype = "INT1U")
    

    # FIG Deviation (Phys - Corr)

    
    # 1. Non-Infected (NI) - Future
    diff_ni_dev <- (r_corr_fut * 10) + r_ni_fut
    terra::writeRaster(diff_ni_dev, file.path(path_figX, paste0("FIGX_corr-phys_NI_", ac, "_", ft, ".tif")), 
                       overwrite=TRUE, datatype = "INT1U")
    
    # 2. Infected (I) - Future
    diff_i_dev <- (r_corr_fut * 10) + r_i_fut
    terra::writeRaster(diff_i_dev, file.path(path_figX, paste0("FIGX_corr-phys_I_", ac, "_", ft, ".tif")), 
                       overwrite=TRUE, datatype = "INT1U")
    
    # 3. Non-Infected (NI) - Present
    diff_ni_pres <- (r_corr_pres * 10) + r_ni_pres
    terra::writeRaster(diff_ni_pres, file.path(path_figX, paste0("FIGX_corr-phys_NI_", ac, "_present.tif")), 
                       overwrite=TRUE, datatype = "INT1U")
    
    # 4. Infected (I) - Present
    diff_i_pres <- (r_corr_pres * 10) + r_i_pres
    terra::writeRaster(diff_i_pres, file.path(path_figX, paste0("FIGX_corr-phys_I_", ac, "_present.tif")), 
                       overwrite=TRUE, datatype = "INT1U")
  }
}


# FIG Seasonal Overlap

modelos <- c("correlative", "noninfected", "infected")
scenarios_all <- c("present", futures) 

for(mod in modelos) {
  for(sce in scenarios_all) {
    message("Processing seasonal overlap: ", mod, " | ", sce)
    
    f17_idx <- grepl(mod, bin_files) & grepl("acc17", bin_files) & grepl(sce, bin_files)
    f25_idx <- grepl(mod, bin_files) & grepl("acc25", bin_files) & grepl(sce, bin_files)
    
    file_17 <- bin_files[f17_idx]
    file_25 <- bin_files[f25_idx]
    
    if(length(file_17) > 0 && length(file_25) > 0) {
      r17 <- terra::rast(file_17[1]) # [1] ensures only one file is taken if there are duplicates
      r25 <- terra::rast(file_25[1])
      
      # Logical Operation: (1 AND 1 = 1)
      seasonal_overlap <- (r17 * r25)
      
      # Save the result
      filename <- paste0("Seasonal_Overlap_", mod, "_", sce, ".tif")
      terra::writeRaster(seasonal_overlap, 
                         file.path(path_figY, filename), 
                         overwrite = TRUE, datatype = "INT1U")
    } else {
      message("  -> Warning: Files not found for ", mod, " | ", sce)
    }
  }
}

message("\nDone!")
